### ISSUE TITLE
Http error: 404

### ISSUE THREAD

**Issue by romainGuiet** [ksugar/samapi#2]
Hi @ksugar ,

thank you for making this tool available ! 

The installation went smoothly but after starting the app:

ˋˋˋ
(samapi) C:\Users\guiet>uvicorn samapi.main:app
INFO:     Started server process [43704]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ˋˋˋ
and setting the server url : 

<img width="253" alt="image" src="https://github.com/ksugar/samapi/assets/8309560/7c8c101b-df51-4784-bedb-1266ba59bdaf">

After enabling SAM ViT-H, I created my first rectangle and got an error

<img width="318" alt="image" src="https://github.com/ksugar/samapi/assets/8309560/46ee621b-aee3-4e9e-97d5-0e2855f835d8">

I tested RGB transmission image and fluorescence image, with the 3 different models...

Thank you for your help,

Cheers,

Romain

**Comment by ksugar** [comment]
Hi @romainGuiet , thank you for trying it! The URL needs to be the complete endpoint URL including `/sam/`.
Could you try putting the following URL?

http://127.0.0.1:8000/sam/

**Comment by romainGuiet** [comment]
it works on the RGB transmission ! thanks 🥳

<img width="787" alt="image" src="https://github.com/ksugar/samapi/assets/8309560/5d721494-8713-4e08-a893-0cdcfd7432d1">

but on my fluorescent image with 5 channels I get an error 

```
INFO:     127.0.0.1:64372 - "POST /sam/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\samapi\main.py", line 80, in predict_sam
    image = decode_image(body.b64img)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\samapi\utils.py", line 13, in decode_image
    return np.array(Image.open(io.BytesIO(base64.b64decode(b64data))))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guiet\.conda\envs\samapi\Lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001B1DCD2FFB0>
```

<img width="784" alt="image" src="https://github.com/ksugar/samapi/assets/8309560/106eee18-9093-4797-adbf-f8d150130cb3">

I tried to reduce the number of displayed channels to 3 but without any positve effect 😅 

Best

Romain

**Comment by ksugar** [comment]
That's great it works for your RGB data! 👍 
At the moment, it assumes grayscale or RGB images. I will try to find a workaround.
@petebankhead do you have a [readRegion](https://qupath.github.io/javadoc/docs/qupath/lib/images/servers/ImageServer.html#readRegion(double,int,int,int,int)) method that returns an RGB BufferedImage as shown in QuPath?

**Comment by petebankhead** [comment]
Hi `readRegion` will return whichever kind of `BufferedImage` is required for the bit-depth and channels - so it's RGB where possible, but could be something else.

If it's something else, then there's a strong chance `ImageIO` won't be able to write the image.

I understand you're using [base64 in the end with PNG](https://github.com/ksugar/qupath-extension-cellsparse/blob/b05cc38f5e8074ee628ca429250b0c41cfb87af4/src/main/java/org/elephant/cellsparse/AbstractCellsparseCommands.java#L33). One way to get a useful byte array to encode is to convert to ImageJ TIFF bytes, e.g.

```java
     public static byte[] getImageBytes(ImageServer<BufferedImage> server, RegionRequest request) throws IOException {
		if (server.isRGB()) {
                     // Do whatever you usually do (PNG should be ok)
                     var img = server.readRegion(request);
                     return // ImageIO code to PNG
                }
         	var imp = IJTools.convertToImagePlus(server, request).getImage();
		return new FileSaver(imp).serialize();
	}
```
where `FileSaver` is a class in ImageJ. I haven't completed or properly tested this code, but I think the idea works, and the (uncompressed) TIFF can be read fine in Python.

Alternatively, if you really want an RGB version (applying whatever settings are used in the viewer), then you can create a [`RenderedImageServer`](https://qupath.github.io/javadoc/docs/qupath/lib/gui/images/servers/RenderedImageServer.html) and get the pixels from that. Although I prefer the solution that sends the raw pixel values, without the rendering to RGB required.

**Comment by ksugar** [comment]
Thanks @petebankhead , both totally make sense. I will use RenderedImageServer for the SAM module.
About the modules for training StarDist/CellPoseI, only grayscale images are supported for now, but I will update them using [TransformedServerBuilder](https://qupath.github.io/javadoc/docs/qupath/lib/images/servers/TransformedServerBuilder.html) as you suggested.
I really appreciate all your help!

**Comment by ksugar** [comment]
@romainGuiet please try [qupath-extension-sam-0.2.0.jar](https://github.com/ksugar/qupath-extension-sam/releases/download/v0.2.0/qupath-extension-sam-0.2.0.jar).
![](https://github.com/ksugar/qupath-extension-sam/releases/download/assets/qupath-sam-5channels-1080p.gif)

@petebankhead [RenderedImageServer](https://qupath.github.io/javadoc/docs/qupath/lib/gui/images/servers/RenderedImageServer.html) works as I expected, thank you again for your help!
