### ISSUE TITLE
Updating api for SAM2

### ISSUE THREAD

**Issue by kess-one** [ksugar/samapi#23]
I keep getting this error message, even on a new build of samapi. Thanks in advance for your help!

```
(samapi) PS C:\Users\K> python -m pip install -U git+https://github.com/ksugar/samapi.git
Collecting git+https://github.com/ksugar/samapi.git
  Cloning https://github.com/ksugar/samapi.git to c:\users\K\appdata\local\temp\pip-req-build-m701ic57
  Running command git clone --filter=blob:none --quiet https://github.com/ksugar/samapi.git 'C:\Users\K\AppData\Local\Temp\pip-req-build-m701ic57'
  Resolved https://github.com/ksugar/samapi.git to commit 4d1652b7e263904041f086902134a7f2a310f8ca
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting mobile_sam@ git+https://github.com/ksugar/MobileSAM.git (from samapi==0.5.0)
  Cloning https://github.com/ksugar/MobileSAM.git to c:\users\K\appdata\local\temp\pip-install-lxd1cb71\mobile-sam_e53dd08925174005a3149ddbace3502e
  Running command git clone --filter=blob:none --quiet https://github.com/ksugar/MobileSAM.git 'C:\Users\K\AppData\Local\Temp\pip-install-lxd1cb71\mobile-sam_e53dd08925174005a3149ddbace3502e'
  Resolved https://github.com/ksugar/MobileSAM.git to commit 41ac534a20a4779fab4f8c84e158ca7c7b40ff26
  Preparing metadata (setup.py) ... done
Collecting sam2@ git+https://github.com/ksugar/segment-anything-2@support-non-cuda (from samapi==0.5.0)
  Cloning https://github.com/ksugar/segment-anything-2 (to revision support-non-cuda) to c:\users\K\appdata\local\temp\pip-install-lxd1cb71\sam2_9c1c5907ccc341f291a359f6b5089e36
  Running command git clone --filter=blob:none --quiet https://github.com/ksugar/segment-anything-2 'C:\Users\K\AppData\Local\Temp\pip-install-lxd1cb71\sam2_9c1c5907ccc341f291a359f6b5089e36'
  Running command git checkout -b support-non-cuda --track origin/support-non-cuda
  branch 'support-non-cuda' set up to track 'origin/support-non-cuda'.
  Switched to a new branch 'support-non-cuda'
  Resolved https://github.com/ksugar/segment-anything-2 to commit fd2b8f3d36aa8fec757b722bd99f138e5265fc45
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\K\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\K\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\K\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\K\AppData\Local\Temp\pip-build-env-6gv20cpa\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\K\AppData\Local\Temp\pip-build-env-6gv20cpa\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\K\AppData\Local\Temp\pip-build-env-6gv20cpa\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "C:\Users\K\AppData\Local\Temp\pip-build-env-6gv20cpa\overlay\Lib\site-packages\torch\__init__.py", line 148, in <module>
          raise err
      OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\K\AppData\Local\Temp\pip-build-env-6gv20cpa\overlay\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by ksugar** [comment]
Hi @kess-one , thank you for reporting the issue.
it seems that you need to install the Visual C++ Redistributable Packages.
https://www.microsoft.com/en-US/download/details.aspx?id=48145&lt

https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969/2

please try the setup again after installing the Visual C++ Redistributable Packages.

**Comment by kess-one** [comment]
I was able to fix it by downloading libomp140_x86_64.dll and moving it to system32.

Found from here: https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969/15

Thank you!
