### ISSUE TITLE
Connection problem with torch 

### ISSUE THREAD

**Issue by mattlitwiller** [ksugar/samapi#31]
Hello,

Thank you for this tool! I've been using the extension in Qupath on my personal PC with no issues, but have been trying to set up the SAM extension for a coworker on their laptop, where I encountered the following issue after following your setup guide in this repo.

```
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

Here is the full error log, which repeats itself seemingly indefinitely until I exit. 

Thank you for any help!

```
(samapi) C:\Users\deptp>uvicorn samapi.main:app --workers 2
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started parent process [2960]
C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\mobile_sam\modeling\tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_5m_224 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\mobile_sam\modeling\tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_5m_224 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\mobile_sam\modeling\tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_11m_224 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\mobile_sam\modeling\tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_11m_224 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\mobile_sam\modeling\tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_21m_224 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\mobile_sam\modeling\tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_21m_224 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\mobile_sam\modeling\tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_21m_384 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\mobile_sam\modeling\tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_21m_384 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\mobile_sam\modeling\tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_21m_512 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\mobile_sam\modeling\tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_21m_512 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\supervisors\multiprocess.py", line 63, in target
    return self.real_target(sockets)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\samapi\main.py", line 291, in <module>
    _register_default_weights()
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\samapi\main.py", line 287, in _register_default_weights
    register_state_dict_from_url(model_type, checkpoint_url, f"default")
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\samapi\main.py", line 272, in register_state_dict_from_url
    raise e
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\samapi\main.py", line 261, in register_state_dict_from_url
    _, filepath = load_state_dict_from_url(
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\samapi\hub_extension.py", line 244, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location), cached_file
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\torch\serialization.py", line 1004, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\torch\serialization.py", line 456, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Process SpawnProcess-2:
Traceback (most recent call last):
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\supervisors\multiprocess.py", line 63, in target
    return self.real_target(sockets)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\samapi\main.py", line 291, in <module>
    _register_default_weights()
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\samapi\main.py", line 287, in _register_default_weights
    register_state_dict_from_url(model_type, checkpoint_url, f"default")
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\samapi\main.py", line 272, in register_state_dict_from_url
    raise e
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\samapi\main.py", line 261, in register_state_dict_from_url
    _, filepath = load_state_dict_from_url(
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\samapi\hub_extension.py", line 244, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location), cached_file
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\torch\serialization.py", line 1004, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\deptp\anaconda3\envs\samapi\lib\site-packages\torch\serialization.py", line 456, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by ksugar** [comment]
Hi @mattlitwiller, thank you for trying samapi and sharing this issue.

It looks like it's the same error reported previously.
https://github.com/ksugar/samapi/issues/28

Please try the following solution.
https://github.com/ksugar/samapi/issues/28#issuecomment-2380648713

I hope this solves the issue, but if it doesn’t, I’d be happy to support further.

**Comment by mattlitwiller** [comment]
> Hi @mattlitwiller, thank you for trying samapi and sharing this issue.
> 
> It looks like it's the same error reported previously. #28
> 
> Please try the following solution. [#28 (comment)](https://github.com/ksugar/samapi/issues/28#issuecomment-2380648713)
> 
> I hope this solves the issue, but if it doesn’t, I’d be happy to support further.

Thanks for pointing this out to me so quickly! That fixed it for me as well.  Cheers!

**Comment by TiTian25** [comment]
> > Hi [@mattlitwiller](https://github.com/mattlitwiller), thank you for trying samapi and sharing this issue.
> > It looks like it's the same error reported previously. [#28](https://github.com/ksugar/samapi/issues/28)
> > Please try the following solution. [#28 (comment)](https://github.com/ksugar/samapi/issues/28#issuecomment-2380648713)
> > I hope this solves the issue, but if it doesn’t, I’d be happy to support further.
> 
> Thanks for pointing this out to me so quickly! That fixed it for me as well. Cheers!

Are you solve?
