### ISSUE TITLE
windows installation issues

### ISSUE THREAD

**Issue by mezwick** [ksugar/samapi#4]
Hi,

I am on windows 10. 

I set up a samapi enviroment with the following commands as per the guide
```
conda create -n samapi -y python=3.11
conda activate samapi
conda install -y cudatoolkit=11.8
```
I had issues downloading .whl file for CUDA via pip, so used the following for conda instead
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
```

This all installed fine. But now when i run 
```
uvicorn samapi.main:app
```

I get the following error
```
Downloading: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth" to C:\Users\U062951/.cache\torch\hub\checkpoints\sam_vit_h_4b8939.pth
Traceback (most recent call last):
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\http\client.py", line 976, in send
    self.connect()
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\http\client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\U062951\Miniconda3\envs\samapi\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\uvicorn\main.py", line 410, in main
    run(
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\uvicorn\config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\samapi\main.py", line 26, in <module>
    ModelType.vit_h: load_state_dict_from_url(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\torch\hub.py", line 746, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\site-packages\torch\hub.py", line 611, in download_url_to_file
    u = urlopen(req)
        ^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U062951\Miniconda3\envs\samapi\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)>

```

Coud you please advise what might be the issue or how to fix?

Thanks!

**Comment by ksugar** [comment]
Hi @mezwick , thank you for reporting the issue.
> I had issues downloading .whl file for CUDA via pip
could you share the issues you had with the following command?

```bash
python -m pip install torch --index-url https://download.pytorch.org/whl/cu118
```

Thank you @lacan for sharing it!
@mezwick please try Mamba instead of Conda and let us know if it works.

**Comment by mezwick** [comment]
Thanks for the replies @lacan and @ksugar 

For the pip command.
`python -m pip install torch --index-url https://download.pytorch.org/whl/cu118`

I return the following error. 
```
(samapi2) C:\Users\U062951>python -m pip install torch --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)'))': /whl/cu118/torch/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)'))': /whl/cu118/torch/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)'))': /whl/cu118/torch/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)'))': /whl/cu118/torch/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)'))': /whl/cu118/torch/
Could not fetch URL https://download.pytorch.org/whl/cu118/torch/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='download.pytorch.org', port=443): Max retries exceeded with url: /whl/cu118/torch/ (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)'))) - skipping
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
Could not fetch URL https://download.pytorch.org/whl/cu118/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='download.pytorch.org', port=443): Max retries exceeded with url: /whl/cu118/pip/ (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)'))) - skipping
```

I work at a company where firewalls may be linked to this error. If i try to manually download .whl files, they do not download (i just get a blank file). Installing via conda seems to work though, hence why i went with a conda install

**Comment by mezwick** [comment]
Downgrading to openssl=1.1.1 seems to have worked. Or at least i seem to now be able to download the fbaipublicfiles and run the server!

```
(samapi2) C:\Users>uvicorn samapi.main:app
Downloading: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth" to C:\Users\U062951/.cache\torch\hub\checkpoints\sam_vit_h_4b8939.pth
100.0%
Downloading: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth" to C:\Users\U062951/.cache\torch\hub\checkpoints\sam_vit_l_0b3195.pth
100.0%
Downloading: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth" to C:\Users\U062951/.cache\torch\hub\checkpoints\sam_vit_b_01ec64.pth
100.0%
[32mINFO[0m:     Started server process [[36m12528[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
```

**Comment by mezwick** [comment]
i can confirm i am up and running. The QuPath exension is working fantastically and my cell annotations efficency has sped up! Excited to get going. Thanks for your help @lacan @ksugar

**Comment by ksugar** [comment]
@mezwick thank you for sharing it. It looks like a temporal issue with PyTorch's repository for the whl files.

https://github.com/pytorch/pytorch/issues/33292

I confirmed that you had found a workaround using the conda package with openssl.

There would be some other possible workarounds.

1. Use another repository for the whl.

```bash
python -m pip install torch --find-links https://s3.amazonaws.com/pytorch/whl/torch_stable.html
```

2. Trust the relevant hosts to ignore the HTTPS warnings.

```bash
python -m pip install --trusted-host pypi.org --trusted-host pytorch.org --trusted-host download.pytorch.org --trusted-host files.pypi.org --trusted-host files.pytorch.org torch --index-url https://download.pytorch.org/whl/cu118
```
